services:      
  pgsql:
    image: postgres:16-bullseye
    container_name: pgsql_vendas
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - ./.docker/postgresql:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
        - app-vendas

networks:
  app-vendas:
    driver: bridge