services:
  app-backend:
    build: 
      context: .
      dockerfile: ./deploy/Dockerfile.local
      args:
        ENVIRONMENT: "local"
    image: app-vendas-backend-local
    container_name: app-vendas-backend-local
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:o+rw
    networks:
      - app-vendas

networks:
  app-vendas:
    driver: bridge